const creditsObj = {
      table: 'Image by <a href="https://pixabay.com/users/sam651030-2106891/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3131322">二 毛</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3131322">Pixabay</a>',
      outdoors: 'Image by <a href="https://pixabay.com/users/knd61-6863349/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4402055">HIROAKI KANEDA</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4402055">Pixabay</a>',
      togo: 'Image by <a href="https://pixabay.com/users/lounisais-811940/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=654832">Lounis Aissaoui</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=654832">Pixabay</a>',
      peach: 'Image by <a href="https://pixabay.com/users/manseok_kim-1005494/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=5810973">manseok Kim</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=5810973">Pixabay</a>',
      berry: 'Image by Bacanski from <a href="https://pixnio.com/author/bicanski">Pixnio</a>',
      honeydew: 'Image by <a href="https://commons.wikimedia.org/wiki/User:Infrogmation">Infrogmation</a> from <a href="https://commons.wikimedia.org/wiki/File:BubbleTeaHoneydewMapleStreet20July2008.jpg">Wikimedia</a>',
      interior: 'Image by <a href="https://commons.wikimedia.org/wiki/User:Takeaway">Takeaway</a> from <a href="https://commons.wikimedia.org/wiki/File:2019_02_Awesome_Coffee_Shop_in_Korat.jpg">Wikimedia</a>',
      southern: 'Image by <a href="https://pxhere.com/en/photographer/147056">Fox</a> from <a href="https://pxhere.com/en/photo/1512057">PxHere</a>',
      arnie: 'Image by Ian L from <a href="https://www.publicdomainpictures.net/en/view-image.php?image=160745&picture=iced-lemon-tea">Public Domain Pictures</a>',
      beach: 'Image by <a href="https://pixabay.com/users/julius_silver-4371822/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3998261">Julius Silver</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3998261">Pixabay</a>',
      wood: 'Image by <a href="https://pixabay.com/users/pexels-2286921/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1846972">Pexels</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1846972">Pixabay</a>',
   }

export default creditsObj